In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../datasets/balloons.csv')

In [3]:
df

color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  ADULT        T
2   YELLOW  SMALL  STRETCH  ADULT        T
3   YELLOW    NaN  STRETCH  ADULT        T
4   YELLOW  SMALL  STRETCH  ADULT        T
..     ...    ...      ...    ...      ...
95  PURPLE  LARGE      DIP  CHILD        F
96  PURPLE  LARGE      DIP  CHILD        F
97  PURPLE  LARGE      DIP  CHILD        F
98  PURPLE  LARGE      DIP  CHILD        F
99  PURPLE  LARGE      DIP  CHILD        F

[100 rows x 5 columns]

In [4]:
df.isna().any()

color       False
size         True
act          True
age          True
inflated    False
dtype: bool

In [5]:
df.isna().sum()

color       0
size        1
act         1
age         1
inflated    0
dtype: int64

In [7]:
df.dropna(axis=0, inplace=True)

In [8]:
df.isna().any()

color       False
size        False
act         False
age         False
inflated    False
dtype: bool

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
Y = df['inflated']
X = df.drop('inflated', axis=1)

In [12]:
feature_names = X.columns

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=123, stratify=Y)

In [15]:
X_train.shape

(72, 4)

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
encoder = OrdinalEncoder()

In [18]:
encoder.fit(X_train)

OrdinalEncoder()

In [19]:
X_train = encoder.transform(X_train)

In [20]:
X_test = encoder.transform(X_test)

In [21]:
from sklearn.naive_bayes import CategoricalNB

In [22]:
model = CategoricalNB()

In [23]:
model.fit(X_train, y_train)

CategoricalNB()

In [24]:
model.category_count_

[array([[21., 23.],
        [17., 11.]]),
 array([[22., 22.],
        [15., 13.]]),
 array([[32., 12.],
        [ 0., 28.]]),
 array([[16.,  1., 27.],
        [28.,  0.,  0.]])]

In [25]:
model.class_count_

array([44., 28.])

In [26]:
y_train_pred = model.predict(X_train)

In [27]:
y_test_pred = model.predict(X_test)

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_train, y_train_pred)

array([[43,  1],
       [ 0, 28]])

In [30]:
confusion_matrix(y_test, y_test_pred)

array([[15,  0],
       [ 0, 10]])