In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
data = pd.read_csv('../datasets/balloons.csv')

In [4]:
data

color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  ADULT        T
2   YELLOW  SMALL  STRETCH  ADULT        T
3   YELLOW    NaN  STRETCH  ADULT        T
4   YELLOW  SMALL  STRETCH  ADULT        T
..     ...    ...      ...    ...      ...
95  PURPLE  LARGE      DIP  CHILD        F
96  PURPLE  LARGE      DIP  CHILD        F
97  PURPLE  LARGE      DIP  CHILD        F
98  PURPLE  LARGE      DIP  CHILD        F
99  PURPLE  LARGE      DIP  CHILD        F

[100 rows x 5 columns]

In [5]:
data.isna().any()

color       False
size         True
act          True
age          True
inflated    False
dtype: bool

In [6]:
data.isna().sum()

color       0
size        1
act         1
age         1
inflated    0
dtype: int64

In [8]:
data.dropna(axis=0, inplace=True)

In [9]:
data.isna().any().any()

False

In [10]:
data

color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  ADULT        T
2   YELLOW  SMALL  STRETCH  ADULT        T
4   YELLOW  SMALL  STRETCH  ADULT        T
6   YELLOW  SMALL  STRETCH  ADULT        T
..     ...    ...      ...    ...      ...
95  PURPLE  LARGE      DIP  CHILD        F
96  PURPLE  LARGE      DIP  CHILD        F
97  PURPLE  LARGE      DIP  CHILD        F
98  PURPLE  LARGE      DIP  CHILD        F
99  PURPLE  LARGE      DIP  CHILD        F

[97 rows x 5 columns]

In [11]:
Y = data['inflated']
X = data.drop('inflated', axis=1)

In [12]:
feature_names = X.columns

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
X, Y, test_size=0.25, random_state=123, stratify=Y
)

In [14]:
X_train.shape

(72, 4)

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
encoder = OrdinalEncoder()

In [17]:
encoder.fit(X_train)

OrdinalEncoder()

In [18]:
X_train = encoder.transform(X_train)

In [19]:
X_test = encoder.transform(X_test)

In [20]:
X_train

array([[1., 1., 0., 2.],
       [1., 1., 1., 0.],
       [1., 1., 0., 2.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 1., 2.],
       [0., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 2.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 2.],
       [1., 1., 1., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 2.],
       [0., 0., 1., 2.],
       [1., 0., 1., 2.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 2.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 2.],
       [1., 0., 1., 2.],
       [0., 1., 0., 2.],
       [0., 1., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 2.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 2.],
       [1., 0., 0., 2.],


In [21]:
from sklearn.naive_bayes import CategoricalNB

In [22]:
model = CategoricalNB()

In [24]:
model.fit(X_train, y_train)

CategoricalNB()

In [25]:
model.category_count_

[array([[21., 23.],
        [17., 11.]]),
 array([[22., 22.],
        [15., 13.]]),
 array([[32., 12.],
        [ 0., 28.]]),
 array([[16.,  1., 27.],
        [28.,  0.,  0.]])]

In [26]:
model.class_count_

array([44., 28.])

In [30]:
y_train_pred = model.predict(X_train)

In [32]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(y_train, y_train_pred)

array([[43,  1],
       [ 0, 28]])

In [28]:
y_test_pred = model.predict(X_test)

In [37]:
confusion_matrix(y_test, y_test_pred)

array([[15,  0],
       [ 0, 10]])

In [38]:
# kalsifikacija teksta

In [39]:
from sklearn.feature_extraction import DictVectorizer

In [40]:
dv = DictVectorizer()

In [ ]:
dv.fit(X_train)
print(f'Broj atributa (razlicitih u dokumentima: ) {len(dv.feature_names_)}')


sparse_matrix = dv.transform(X_train)

X_train = pd.DataFrame(sparse_matrix.toarray(), columns=dv.feature_names_)


X_train.head()

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

model.class_count_

model.feature_count_

y_train_pred = model.predict(X_train)

confusion_matrix(y_train, y_train_pred)

